export const RES_NET_CODE = '10000'
export const RES_CODE_SUCCESS = '0000'
export const RES_CODE_NO_AUTH = 'E100'
export const RES_CODE_SIGN_ERROR = 'E101'
export const RES_CODE_DATA_ERROR = 'E102'
export const RES_CODE_TIMESTAMPE_EXPIRE = 'E103'
export const RES_CODE_PARAM_ERROR = 'E104'
export const RES_CODE_BANK_RESPONSE = 'E105'
export const RES_CODE_SECURITY_ERROR = 'E106'
export const RES_CODE_AUTH_EXPIRE = 'E107'
export const RES_CODE_REATHOR = 'E110'
export const RES_CODE_SYSTEM_ERROR = 'U999'

